---
- name: Validate sshd config
  ansible.builtin.command: sshd -t
  changed_when: false
  listen: Validate sshd config

- name: Reload ssh service
  ansible.builtin.service:
    name: ssh
    state: reloaded
  listen: Reload ssh service
