[[apps.rpm]]
name = "cc-switch"
repo = "farion1231/cc-switch"
package_names = ["cc-switch", "CC-Switch"]
# asset_regex = "x86_64.*\\.rpm$"
# renovate: datasource=github-releases depName=farion1231/cc-switch versioning=semver
version = "v3.17.0"

[[apps.rpm]]
name = "clash-verge-rev"
repo = "clash-verge-rev/clash-verge-rev"
package_names = ["clash-verge", "clash-verge-rev", "Clash.Verge"]
# renovate: datasource=github-releases depName=clash-verge-rev/clash-verge-rev versioning=semver
version = "v2.5.2"

[[apps.rpm]]
name = "biopass-rs"
repo = "YewFence/biopass-rs"
package_names = ["biopass-rs"]
# renovate: datasource=github-releases depName=YewFence/biopass-rs versioning=semver
version = "v0.6.11"

[[apps.rpm]]
name = "motrix-next"
repo = "AnInsomniacy/motrix-next"
package_names = ["MotrixNext", "motrix-next", "motrixnext"]
# renovate: datasource=github-releases depName=AnInsomniacy/motrix-next versioning=semver
version = "v3.9.6"

[[apps.appimage]]
name = "paseo"
repo = "getpaseo/paseo"
app_name = "Paseo"
# renovate: datasource=github-releases depName=getpaseo/paseo versioning=semver
version = "v0.1.107"

[[apps.kpackage]]
name = "waywallen-display-kde"
repo = "waywallen/waywallen-display"
package_id = "org.waywallen.kde"
package_type = "Plasma/Wallpaper"
asset_regex = "^waywallen-kde-.*-embed\\.zip$"
# renovate: datasource=github-releases depName=waywallen/waywallen-display versioning=semver
version = "v0.2.8"
