name = "motrix-next"
repo = "AnInsomniacy/motrix-next"
package_names = ["MotrixNext", "motrix-next", "motrixnext"]
# renovate: datasource=github-releases depName=AnInsomniacy/motrix-next versioning=semver
version = "v4.0.0"

[[apps.appimage]]
name = "paseo"
repo = "getpaseo/paseo"
app_name = "Paseo"
# renovate: datasource=github-releases depName=getpaseo/paseo versioning=semver
version = "v0.5.0"

[[apps.kpackage]]
name = "waywallen-display-kde"
repo = "waywallen/waywallen-display"
package_id = "org.waywallen.kde"
package_type = "Plasma/Wallpaper"
asset_regex = "^waywallen-kde-.*-embed\\.zip$"
# renovate: datasource=github-releases depName=waywallen/waywallen-display versioning=semver
version = "v0.4.1"
