[tools]
ansible = { version = "latest", pipx_args = "--include-deps", uvx = "false" }
"github:YewFence/YewSeal" = "latest"
"pipx:ansible-lint" = "latest"

[env]
ANSIBLE_CONFIG = "{{config_root}}/ansible/ansible.cfg"
ANSIBLE_COLLECTIONS_SCAN_SYS_PATH = "true"
ANSIBLE_LOCAL_TEMP = "{{config_root}}/.ansible/tmp"

[tasks.play-dev]
run = "ansible-playbook -i ansible/inventory.yml ansible/init-devbox.yml"
