[tools]
uv = "latest"
python = "3.14"
"github:YewFence/YewSeal" = "latest"

[env]
ANSIBLE_CONFIG = "{{config_root}}/ansible/ansible.cfg"
ANSIBLE_COLLECTIONS_SCAN_SYS_PATH = "true"
ANSIBLE_LOCAL_TEMP = "{{config_root}}/.ansible/tmp"

[tasks.play-dev]
run = "uv run ansible-playbook -i ansible/inventory.yml ansible/init-devbox.yml"
[tasks.play-server]
run = "uv run ansible-playbook -i ansible/inventory.yml ansible/init-server.yml"
