---
enable_mise: true
dev_enable_oh_my_zsh: true
dev_enable_zellij: true
dev_enable_docker: false
dev_enable_tailscale: false
dev_enable_agent_software: false
mise_enable_dev_tools: true
mise_tools_dev:
  "zellij": latest
  "gh": latest
  "github:Apts-1547/gcop-rs": latest
  "uv": latest
  "node": lts
devbox_network_manage: false
devbox_network_preset: disabled
devbox_network_backend: disabled
devbox_network_interface: ""
devbox_network_gateway: ""
devbox_network_dns_servers: []
devbox_network_static_ipv4: ""
