---
- name: Add shell aliases to {{ shell_aliases_rc_file }}
  ansible.builtin.blockinfile:
    path: "{{ shell_aliases_rc_file }}"
    create: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0644"
    marker: "# {mark} YewNeedles Shell Aliases"
    block: |
      {% for item in shell_aliases_entries %}
      {% if item.enabled | bool %}
      alias {{ item.alias }}
      {% endif %}
      {% endfor %}
