[tools.mise]
scopes = ["global"]
command = ["mise", "completion", "zsh"]

[tools.gh]
scopes = ["global"]
command = ["gh", "completion", "-s", "zsh"]

[tools.starship]
scopes = ["global"]
command = ["starship", "completions", "zsh"]

[tools.rclone]
scopes = ["global"]
command = ["rclone", "completion", "zsh", "-"]

[tools.kubectl]
scopes = ["project"]
command = ["kubectl", "completion", "zsh"]

[tools.helm]
scopes = ["project"]
command = ["helm", "completion", "zsh"]

[tools.uv]
scopes = ["project"]
command = ["uv", "generate-shell-completion", "zsh"]

[tools.pnpm]
scopes = ["global", "project"]
command = ["pnpm", "completion", "zsh"]

[tools.aube]
scopes = ["project"]
command = ["aube", "completion", "zsh"]

[tools.bun]
scopes = ["project"]
command = ["bun", "completion", "zsh"]

[tools.chezmoi]
scopes = ["global"]
command = ["chezmoi", "completion", "zsh"]
